version: "2"
services:
  node:
    image: app-react
    build:
      context: ./app-react
    tty: true
    stdin_open: true
    privileged: true
    command: bash -c "cd /app-react;  yarn start"
    #command: bash -c "bash /usr/local/bin/docker-entrypoint.sh;  /bin/bash"
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
